---
- name: Restart Docker Service and Run Docker Compose
  hosts: all
  become: yes
  tasks:
#    - name: Restart Docker service
#     ansible.builtin.service:
#        name: docker
#        state: restarted
        
    - name: run
      ansible.builtin.command: ls -l
      args:
        chdir: /home/ubuntu/
