---
- name: Restart Docker Service and Run Docker Compose
  hosts: all
  become: yes
  tasks:
    - name: Restart Docker service
      ansible.builtin.service:
        name: docker
        state: restarted

    - name: Start Docker Service
      
      cmd: sudo docker compose up  
      args:
        chdir: /home/ubuntu/easyTravel-Docker/
